[package]
name = "bolt12-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Decode and verify BOLT12 offers, invoices, and payer proofs"
readme = "../README.md"
documentation = "https://docs.rs/bolt12-common"
homepage = "https://github.com/vincenzopalazzo/bolt12-cli"
keywords = ["bitcoin", "lightning", "bolt12"]
categories = ["encoding"]

[dependencies]
bech32.workspace = true
lightning.workspace = true
serde.workspace = true
thiserror.workspace = true
chrono = { workspace = true }

[dev-dependencies]
chrono = { workspace = true }
serde.workspace = true
serde_json.workspace = true
