[workspace]
resolver = "2"
members = ["bolt12-common", "bolt12-cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vincenzopalazzo/bolt12-cli"
authors = ["Vincenzo Palazzo <vincenzopalazzodev@gmail.com>"]

[workspace.dependencies]
bech32 = { version = "0.11", default-features = false, features = ["alloc"] }
lightning = { git = "https://github.com/lightningdevkit/rust-lightning", rev = "054c95ae10879627d157f1ffbbc51d4b95b08711", default-features = false, features = ["std"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
